/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as CellNavigationRouteImport } from './routes/CellNavigation'
import { Route as AnimationRouteImport } from './routes/Animation'
import { Route as AllFeaturesRouteImport } from './routes/AllFeatures'
import { Route as IndexRouteImport } from './routes/index'

const CellNavigationRoute = CellNavigationRouteImport.update({
  id: '/CellNavigation',
  path: '/CellNavigation',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimationRoute = AnimationRouteImport.update({
  id: '/Animation',
  path: '/Animation',
  getParentRoute: () => rootRouteImport,
} as any)
const AllFeaturesRoute = AllFeaturesRouteImport.update({
  id: '/AllFeatures',
  path: '/AllFeatures',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/AllFeatures': typeof AllFeaturesRoute
  '/Animation': typeof AnimationRoute
  '/CellNavigation': typeof CellNavigationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/AllFeatures': typeof AllFeaturesRoute
  '/Animation': typeof AnimationRoute
  '/CellNavigation': typeof CellNavigationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/AllFeatures': typeof AllFeaturesRoute
  '/Animation': typeof AnimationRoute
  '/CellNavigation': typeof CellNavigationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/AllFeatures' | '/Animation' | '/CellNavigation'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/AllFeatures' | '/Animation' | '/CellNavigation'
  id: '__root__' | '/' | '/AllFeatures' | '/Animation' | '/CellNavigation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllFeaturesRoute: typeof AllFeaturesRoute
  AnimationRoute: typeof AnimationRoute
  CellNavigationRoute: typeof CellNavigationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/AllFeatures': {
      id: '/AllFeatures'
      path: '/AllFeatures'
      fullPath: '/AllFeatures'
      preLoaderRoute: typeof AllFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Animation': {
      id: '/Animation'
      path: '/Animation'
      fullPath: '/Animation'
      preLoaderRoute: typeof AnimationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/CellNavigation': {
      id: '/CellNavigation'
      path: '/CellNavigation'
      fullPath: '/CellNavigation'
      preLoaderRoute: typeof CellNavigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid-table/Table': {
      id: '/grid-table/Table'
      path: ''
      fullPath: '/grid-table/Table'
      preLoaderRoute: unknown
      parentRoute: typeof rootRouteImport
    }
    '/grid-table/type': {
      id: '/grid-table/type'
      path: ''
      fullPath: '/grid-table/type'
      preLoaderRoute: unknown
      parentRoute: typeof rootRouteImport
    }
    '/grid-table/hook/constant': {
      id: '/grid-table/hook/constant'
      path: ''
      fullPath: '/grid-table/hook/constant'
      preLoaderRoute: unknown
      parentRoute: typeof rootRouteImport
    }
    '/grid-table/hook/utils': {
      id: '/grid-table/hook/utils'
      path: ''
      fullPath: '/grid-table/hook/utils'
      preLoaderRoute: unknown
      parentRoute: typeof rootRouteImport
    }
  }
}

declare module './routes/index' {
  const createFileRoute: CreateFileRoute<
    '/',
    FileRoutesByPath['/']['parentRoute'],
    FileRoutesByPath['/']['id'],
    FileRoutesByPath['/']['path'],
    FileRoutesByPath['/']['fullPath']
  >
}
declare module './routes/AllFeatures' {
  const createFileRoute: CreateFileRoute<
    '/AllFeatures',
    FileRoutesByPath['/AllFeatures']['parentRoute'],
    FileRoutesByPath['/AllFeatures']['id'],
    FileRoutesByPath['/AllFeatures']['path'],
    FileRoutesByPath['/AllFeatures']['fullPath']
  >
}
declare module './routes/Animation' {
  const createFileRoute: CreateFileRoute<
    '/Animation',
    FileRoutesByPath['/Animation']['parentRoute'],
    FileRoutesByPath['/Animation']['id'],
    FileRoutesByPath['/Animation']['path'],
    FileRoutesByPath['/Animation']['fullPath']
  >
}
declare module './routes/CellNavigation' {
  const createFileRoute: CreateFileRoute<
    '/CellNavigation',
    FileRoutesByPath['/CellNavigation']['parentRoute'],
    FileRoutesByPath['/CellNavigation']['id'],
    FileRoutesByPath['/CellNavigation']['path'],
    FileRoutesByPath['/CellNavigation']['fullPath']
  >
}
declare module './routes/grid-table/Table' {
  const createFileRoute: CreateFileRoute<
    '/grid-table/Table',
    FileRoutesByPath['/grid-table/Table']['parentRoute'],
    FileRoutesByPath['/grid-table/Table']['id'],
    FileRoutesByPath['/grid-table/Table']['path'],
    FileRoutesByPath['/grid-table/Table']['fullPath']
  >
}
declare module './routes/grid-table/type' {
  const createFileRoute: CreateFileRoute<
    '/grid-table/type',
    FileRoutesByPath['/grid-table/type']['parentRoute'],
    FileRoutesByPath['/grid-table/type']['id'],
    FileRoutesByPath['/grid-table/type']['path'],
    FileRoutesByPath['/grid-table/type']['fullPath']
  >
}
declare module './routes/grid-table/hook/constant' {
  const createFileRoute: CreateFileRoute<
    '/grid-table/hook/constant',
    FileRoutesByPath['/grid-table/hook/constant']['parentRoute'],
    FileRoutesByPath['/grid-table/hook/constant']['id'],
    FileRoutesByPath['/grid-table/hook/constant']['path'],
    FileRoutesByPath['/grid-table/hook/constant']['fullPath']
  >
}
declare module './routes/grid-table/hook/utils' {
  const createFileRoute: CreateFileRoute<
    '/grid-table/hook/utils',
    FileRoutesByPath['/grid-table/hook/utils']['parentRoute'],
    FileRoutesByPath['/grid-table/hook/utils']['id'],
    FileRoutesByPath['/grid-table/hook/utils']['path'],
    FileRoutesByPath['/grid-table/hook/utils']['fullPath']
  >
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllFeaturesRoute: AllFeaturesRoute,
  AnimationRoute: AnimationRoute,
  CellNavigationRoute: CellNavigationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
